version: '3.8'

services:
  client:
    build: ./client
    container_name: share-it-client
    ports:
    - "192.168.1.2:5173:5173" # replace with your local ip
    working_dir: /app
    env_file:
    - ./client/.env
    command: npm run dev:host

  server:
    build: ./server
    container_name: share-it-server
    ports:
    - "192.168.1.2:8000:8000" # replace with your local ip
    working_dir: /app
    command: uvicorn index:app --host 0.0.0.0 --port 8000
